### ISSUE TITLE
An option to remove/add rows?

### ISSUE THREAD

**Issue by dinhanhx** [silverweed/tiers#1]
Thanks for creating this web app. You are amazing. I humbly request a small feature. An option to remove/add rows?

**Comment by silverweed** [comment]
Hello, thanks for the feedback :)
That sounds useful, I'm gonna see what I can do about it.

**Comment by silverweed** [comment]
Implemented in c3109a1.

Note that **this breaks compatibility with older save files**.

**Comment by dinhanhx** [comment]
Thanks. The design is intuitive enough for me.
