### ISSUE TITLE
put the images drop below instead of left side

### ISSUE THREAD

**Issue by derspawn** [silverweed/tiers#10]
can you put the images container below instead like most tier list websites. id do it but I don't know coding that well. more of a CSS person.

**Comment by silverweed** [comment]
Hi, sorry for taking so long to answer. I tried changing the layout to horizontal like you suggested and I think I like it better than the vertical, so I changed it.
For whoever liked the vertical layout better, it is still available in [the `vertical` branch](https://github.com/silverweed/tiers/tree/vertical).

Feel free to comment below about it.
