### ISSUE TITLE
Ability to remove the added images

### ISSUE THREAD

**Issue by ghost** [silverweed/tiers#2]
Hello there, while it is good to be able to add as much stuff as we want to the tier list, sometimes it's possible to add duplicates or the wrong content. For people who add to the list piece by piece and rate in order to get a baseline this can be hard as you have no choice but to start over. It would be pretty epic to have the ability to delete specific images.

**Comment by silverweed** [comment]
Good idea, I added it in d5ed8670d461ffe86b1baa663d964fc187871537
