### ISSUE TITLE
Paste raw image from clipboard

### ISSUE THREAD

**Issue by Blizihguh** [silverweed/tiers#8]
May PR this myself, but I figured I'd open an issue either way. The #1 feature I would want in a tier list maker would be to copy and paste images directly from an image editor, without having to go through the tedious crop -> save file -> open in tier maker app process for every picture I want to add. It seems like this sort of thing is well supported now, although I haven't tried it myself yet:

https://stackoverflow.com/questions/6333814/how-does-the-paste-image-from-clipboard-functionality-work-in-gmail-and-google-c

**Comment by silverweed** [comment]
Hello,
I tried quickly implementing the code in the SO reply in 4dae650 and it seems to be working well, at least on my browser (Firefox).
Feel free to try it and see if it works for you as well!
